config/routes.rb
DiaryFishingTripService::Application.routes.draw do

  root "main#index"

  devise_for :blog_admin, controllers: { sessions: 'blog_admin/sessions' }

  mount RailsAdmin::Engine => '/blog_admin', as: 'rails_admin'

  get '/locations', to: 'locations#index', as: 'locations'
  get '/blog', to: 'blog#index'

  get '/blog/:id', to: 'blog#show', as: 'post'
  # match 'blog/by_year_and_month/:year/:month' => 'blog#by_year_and_month', :as=> :posts_by_year_and_month

  get '/blog//tag/:id', to: 'blog#tag_show', as: 'tag'

  # get '/team', to: 'team#index'
  # get '/video', to: 'team#video', as: 'video'
  get '/team/:id', to: 'team#show', as: 'profile'



  #devise_for :users

  namespace :admin do
    root "main#index"

  end

  namespace :profile do
    root "main#index"

  end

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      get 'locations' => 'location#index', :as => 'locations'
      get 'tackles' => 'tackle#index', :as => 'tackles'
      get 'baits' => 'bait#index', :as => 'baits'
    end
  end


end

app/models/bait.rb
class Bait < ActiveRecord::Base
  belongs_to :bait_category

  attr_accessible :name, :description, :bait_category, :size, :bait_category_id
end

app/models/bait_category.rb
class BaitCategory < ActiveRecord::Base
  has_many :baits
  attr_accessible :name, :description
end

app/models/blog_admin.rb
class BlogAdmin < ActiveRecord::Base
  has_many :posts

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" , :avatar => "242x200>"}

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :avatar, :name, :title, :small_description, :description,
                  :reset_password_sent_at, :remember_created_at, :sign_in_count,
                  :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :admin, :interests
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :description, :lat, :lng
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image,
                    :styles => {:to_main=>"650x350#", :medium => "300x300>", :thumb => "100x100>" }

  attr_accessible :title, :image, :description

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_taggable

  # has_many :post_images

  belongs_to :blog_admin

  attr_accessible :title,:small_description, :description, :title_image, :blog_admin_id, :tag_list, :tag_ids

  has_attached_file :title_image,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }
                    # :url => "/attachments/:id/title_image/:basename_:style.:extension",
                    # :path => ":rails_root/public/attachments/:id/title_image/:basename_:style.:extension"

                    # :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :title_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  scope :by_join_date, -> {
    order("created_at DESC")
  }

end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  # belongs_to :post

  has_attached_file :attacment,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :url => "/attachments/user_:user/attacment/:basename_:style.:extension",
                    :path => ":rails_root/public/attachments/user_:user/attacment/:basename_:style.:extension"
  # :default_url => "/images/:style/missing.png"


end

app/models/tackle.rb
class Tackle < ActiveRecord::Base
  belongs_to :tackle_category

  attr_accessible :name, :description, :tackle_category, :tackle_category_id
end

app/models/tackle_category.rb
class TackleCategory < ActiveRecord::Base
  has_many :tackles
  attr_accessible :name, :description
end

app/models/trip_session.rb
class TripSession < ParseResource::Base
  fields :is_active, :location, :user, :startSession, :endSession

end

app/models/user.rb
class User < ParseUser


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_filter :tag_cloud, :blog_cloud

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def index
    @posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)

  end

  def show
    @post = Post.find(params[:id])
  end

  def tag_show
    @posts = Post.tagged_with(params[:id]).order('created_at DESC')
    # render :action => :index
  end


  def blog_cloud
    @articles_by_month = Post.all.order('created_at DESC').group_by { |article|  Russian::strftime(article.created_at,"%B %Y") }
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    source = 'http://iamfisher.ru/v1/location_json'
    @locations = JSON.parse(open(source).read)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout 'landing'
  def index

    @photos = Photo.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    @team = BlogAdmin.all
  end

  def show
    @profile = BlogAdmin.find(params[:id])
  end

  def video

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/blog_helper.rb
module BlogHelper

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/blog/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 blog-mine">

    <p>
        <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
            <span class="label label-success"> <%= link_to tag.name, tag_url(tag.name), :class => css_class %></span>
        <% end %>
    </p>

    <% @posts.each do |post| %>

        <div class="blog-post row">
          <div class="col-xs-12 col-sm-4" >
            <% if post.title_image.present?  %>
                <%= link_to image_tag( post.title_image.url(:medium), :class => 'img-responsive'), post_url(post) %>
            <% end %>
          </div>
          <div class="col-xs-12 col-sm-8" >
            <div class="page-header">
              <h3><%= link_to post.title, post %></h3>
            </div>
            <p><%= post.small_description %></p>
            <p>
              <% post.tag_list.each do |tag| %>
                  <span class="label label-success"><%= link_to tag, tag_url(tag) %></span>
              <% end %>
            </p>
            <span class="News Date"><%= link_to  post.blog_admin.name, profile_url(post.blog_admin) %> <%= Russian::strftime(post.created_at, "%d %b %Y") %></span>
          </div>
        </div>


    <% end %>

    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>

  <div class="col-xs-12 col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="row">
      <div class="col-xs-12 m-top">
        <!-- VK Widget -->
        <div id="vk_groups"></div>
      </div>
    </div>
    <script type="text/javascript">
      VK.Widgets.Group("vk_groups", {mode: 2, width: "auto", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 99626502);
    </script>

    <div class="sidebar-module">
      <% @articles_by_month.each do |monthname, articles| %>
          <h4><%= monthname %></h4>
      <ol class="list-unstyled">
        <% articles.each do |post| %>
            <li class="archive-post"><%= link_to post.title, post %></li>
        <% end %>
      </ol>
      <% end %>
    </div>


  </div>
</div>

app/views/blog/show.html.erb
<% content_for :title, @post.title %>
<% content_for :description, @post.small_description %>
<% content_for :keywords, @post.small_description %>
<div class="row" style="padding-bottom: 20px;">
  <div class="col-xs-12">



<div class="header">
  <h3 class="media-heading"><%= @post.title %> -<small> <%= link_to @post.blog_admin.name, profile_url(@post.blog_admin) %> </small></h3>


  <p>
    <% @post.tag_list.each do |tag| %>
        <span class="label label-success"><%= link_to tag, tag_url(tag) %></span>
    <% end %>
  </p>


</div>



<div class="article_show" style="padding-bottom: 20px;">
  <%= @post.description.html_safe %>

  <script type="text/javascript" src="//yandex.st/share/share.js"
          charset="utf-8"></script>
  <div style="float: right; " class="yashare-auto-init" data-yashareL10n="ru"
       data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus" data-yashareTheme="counter">

   </div>
    </div>
  </div>
  <div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'diarytrip'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

</div>

app/views/blog/tag_show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12">

    <p>
      <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
          <span class="label label-success"> <%= link_to tag.name, tag_url(tag.name), :class => css_class %></span>
      <% end %>
    </p>

    <% @posts.each do |post| %>

        <div class="blog-post">
          <div class="media">
            <a class="pull-left" href="<%= post_url(post) %>">
              <%= image_tag post.title_image.url(:medium) %>
            </a>

            <div class="media-body">
              <h4 class="media-heading"><%= link_to post.title, post %></h4>
              <p><%= post.small_description %></p>
              <p>
                <% post.tags.each do |tag| %>
                    <span class="label label-success"><%= link_to tag, tag_url(tag.name) %></span>
                <% end %>
              </p>
              <span class="News Date"><%= link_to  post.blog_admin.name, profile_url(post.blog_admin) %> <%= Russian::strftime(post.created_at, "%d %b %Y") %></span>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/team/index.html.erb
<div class="row">
  <% @team.each do |profile| %>
  <div class="col-sm-6 col-md-4">

    <div class="thumbnail">
      <%= image_tag profile.avatar.url(:avatar) %>
      <div class="caption">
        <h3><%= link_to profile.name, profile_url(profile) %></h3>
        <p><%= profile.small_description %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/team/show.html.erb
<% content_for :title, @profile.name %>
<% content_for :description, @profile.small_description %>
<% content_for :keywords, @profile.small_description %>

<h3><%= @profile.name %></h3>
<div class="row">
  <div class="col-xs-5 col-md-5"><%= image_tag @profile.avatar.url(:medium) %></div>
  <div class="col-xs-7 col-md-7">
    <h3><%= @profile.title %></h3>
    <p><b>Интересы - </b><%= @profile.interests %></p>
    <p><%= @profile.description %></p>
  </div>
</div>
<br/>

app/views/team/video.html.erb
<% content_for :title, 'Видео' %>
<%# content_for :description, @profile.small_description %>
<%# content_for :keywords, @profile.small_description %>
<div class="row">
  <div class="col-xs-12 video-container">
    <iframe src="https://www.youtube.com/embed/G4QwQfyJVJs" frameborder="0" allowfullscreen></iframe>
  </div>
</div>