config/routes.rb
DiaryFishingTripService::Application.routes.draw do

  root "main#index"

  devise_for :blog_admin, controllers: { sessions: 'blog_admin/sessions' }

  mount RailsAdmin::Engine => '/blog_admin', as: 'rails_admin'

  get '/locations', to: 'locations#index', as: 'locations'
  get '/blog', to: 'blog#index'

  get '/blog/:id', to: 'blog#show', as: 'post'
  # match 'blog/by_year_and_month/:year/:month' => 'blog#by_year_and_month', :as=> :posts_by_year_and_month

  get '/blog//tag/:id', to: 'blog#tag_show', as: 'tag'

  # get '/team', to: 'team#index'
  # get '/video', to: 'team#video', as: 'video'
  get '/team/:id', to: 'team#show', as: 'profile'



  #devise_for :users

  namespace :admin do
    root "main#index"

  end

  namespace :profile do
    root "main#index"

  end

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      get 'locations' => 'location#index', :as => 'locations'
      get 'tackles' => 'tackle#index', :as => 'tackles'
      get 'baits' => 'bait#index', :as => 'baits'
    end
  end


end

app/models/bait.rb
class Bait < ActiveRecord::Base
  belongs_to :bait_category

  attr_accessible :name, :description, :bait_category, :size, :bait_category_id
end

app/models/bait_category.rb
class BaitCategory < ActiveRecord::Base
  has_many :baits
  attr_accessible :name, :description
end

app/models/blog_admin.rb
class BlogAdmin < ActiveRecord::Base
  has_many :posts

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" , :avatar => "242x200>"}

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :avatar, :name, :title, :small_description, :description,
                  :reset_password_sent_at, :remember_created_at, :sign_in_count,
                  :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :admin, :interests
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :description, :lat, :lng
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image,
                    :styles => {:to_main=>"650x350#", :medium => "300x300>", :thumb => "100x100>" }

  attr_accessible :title, :image, :description

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_taggable

  # has_many :post_images

  belongs_to :blog_admin

  attr_accessible :title,:small_description, :description, :title_image, :blog_admin_id, :tag_list, :tag_ids

  has_attached_file :title_image,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }
                    # :url => "/attachments/:id/title_image/:basename_:style.:extension",
                    # :path => ":rails_root/public/attachments/:id/title_image/:basename_:style.:extension"

                    # :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :title_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  scope :by_join_date, -> {
    order("created_at DESC")
  }

end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  # belongs_to :post

  has_attached_file :attacment,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :url => "/attachments/user_:user/attacment/:basename_:style.:extension",
                    :path => ":rails_root/public/attachments/user_:user/attacment/:basename_:style.:extension"
  # :default_url => "/images/:style/missing.png"


end

app/models/tackle.rb
class Tackle < ActiveRecord::Base
  belongs_to :tackle_category

  attr_accessible :name, :description, :tackle_category, :tackle_category_id
end

app/models/tackle_category.rb
class TackleCategory < ActiveRecord::Base
  has_many :tackles
  attr_accessible :name, :description
end

app/models/trip_session.rb
class TripSession < ParseResource::Base
  fields :is_active, :location, :user, :startSession, :endSession

end

app/models/user.rb
class User < ParseUser


end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_filter :tag_cloud, :blog_cloud

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def index
    @posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)

  end

  def show
    @post = Post.find(params[:id])
  end

  def tag_show
    @posts = Post.tagged_with(params[:id]).order('created_at DESC')
    # render :action => :index
  end


  def blog_cloud
    @articles_by_month = Post.all.order('created_at DESC').group_by { |article|  Russian::strftime(article.created_at,"%B %Y") }
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout 'landing'
  def index

    @photos = Photo.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    @team = BlogAdmin.all
  end

  def show
    @profile = BlogAdmin.find(params[:id])
  end

  def video

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/blog_helper.rb
module BlogHelper

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DiaryTrip - Carpfishing</title>

  <%= stylesheet_link_tag "admin-application", media: "all", "data-turbolinks-track" => true %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin/#/">DiaryTrip</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin/#/settings">Настройки</a></li>
        <li><a href="/admin/#/logout">Выход</a></li>

      </ul>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="/admin/#/users/">Пользователи</a></li>
        <li><a href="/admin/#/locations/">Локации</a></li>
        <li><a href="/admin/#/baits/">Насадки</a></li>
        <li><a href="/admin/#/baits-categories/">Типы насадок</a></li>
        <li><a href="/admin/#/tackles/">Оснастки</a></li>
        <li><a href="/admin/#/tackles-categories/">Типы оснасток</a></li>
        <li><a href="/admin/#/trip-sessions/">Сессии</a></li>

      </ul>

    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      <%= yield %>
    </div>
  </div>
</div>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="rdWvj_TTJ0pnlK0WaCpPxp76rJaT_6a2c11XpXMs2vg"/>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Красивые отчёты с рыбалок где мы пытаемся поймать рыбу своей мечты. Показываем насколько интересной и увлекательной может быть ловля карпа." %>">
  <meta name="keywords" content="<%= content_for?(:keywords) ? yield(:keywords) : "карпфишинг, ловля карпа, рыбалка, карповая ловля, снасти на карпа, бойлы, как поймать карпа, карп, прикормка, бойл, бойлы, пеллетс, ликвид, обзор, монтаж, крючки, оснастка, грузила фан фишинг, ловить рыбу, рыболов, fox, century, delkim, jag, ridge monkey, solar, richworth, ccmoore, fun fishing, esp, gardner, kryston, pva" %>">
  <meta name="author" content="">
  <title><%= content_for?(:title) ? yield(:title) : "Отчёты с рыбалок. Карпфишинг." %></title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header clearfix new_style">
  <!--<ul class="nav nav-pills pull-right " >-->
  <!--<li class="active"><%#= link_to "Главная", root_url %></li>-->
  <!--<li> <%#= link_to "Личный кабинет", profile_root_url %></li>-->
  <!--</ul>-->
  <h3 class="text-muted pull-left hidden-xs" ><%= link_to image_tag('logonew.png', size: '200x235'), root_url %></h3>

<!--  <h3 class="pull-right hidden-xs"><%#= link_to image_tag('carpshop.png', :class => 'img-responsive carphouse'), 'http://carpshop.ru', target: '_blank' %></h3>-->


<div class="row" >
  <div class="col-xs-12">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="menu">
      <%= render_navigation %>
    </div>


  </div>
</div>
</div>
<div class="container">

  <!-- carpfishing.club -->
  <% if !Rails.env.development? %>

      <script type="text/javascript">
          google_ad_client = "ca-pub-2687456701853743";
          google_ad_slot = "1403500859";
          google_ad_width = 728;
          google_ad_height = 90;
      </script>
      <!-- carpfishing.club -->
      <script type="text/javascript"
              src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>
  <% end %>
  <script type="text/javascript" src="//vk.com/js/api/openapi.js?121"></script>

  <%= yield %>

  <div class="footer">
    <p>&copy; CarpFishing.Club 2014
      <% if Time.now.year != 2014 %> - <%= Time.now.year %>
      <% end %></p>
  </div>

</div>
<!-- /container -->





<%= javascript_include_tag "application", "data-turbolinks-track" => true %>


<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function () {
            try {
                w.yaCounter25016279 = new Ya.Metrika({
                    id: 25016279,
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true
                });
            } catch (e) {
            }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () {
                    n.parentNode.insertBefore(s, n);
                };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else {
            f();
        }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript>
  <div><img src="//mc.yandex.ru/watch/25016279" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript>
<!-- /Yandex.Metrika counter -->
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'diarytrip'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script');
        s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="rdWvj_TTJ0pnlK0WaCpPxp76rJaT_6a2c11XpXMs2vg" />
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Карпфишинг как стиль жизни. Рыбалка нового поколения. Преследуем принцип “поймал-отпусти”, стараемся нести его в массы как и бережное отношение к природе" %>">
  <meta name="keywords" content="<%= content_for?(:keywords) ? yield(:keywords) : "карпфишинг, ловля карпа, рыбалка, карповая ловля, снасти на карпа, бойлы, удочки на карпа, сигнализаторы поклевки, карповые палатки, карповый интернет магазин, карповые снасти, ловля карпа, интернет магазин карповых снастей, фан фишинг, ловить рыбу, бойл, стул, раскладушка, спод, удилище, fox, century, delkim, jag, ridge monkey, solar, richworth, ccmoore, fun fishing, esp, gardner, kryston, pva" %>">
  <meta name="author" content="">
  <meta name="yandex-verification" content="d6def23859c99e21" />

  <title><%= content_for?(:title) ? yield(:title) : "Рыбалка. Карпфишинг - трофейная ловля карпа" %></title>

  <%= stylesheet_link_tag  "landing", media: "all", "data-turbolinks-track" => true %>
  <!-- Custom CSS -->

  <!-- Custom Fonts -->
  <!--<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->


  <script type="text/javascript" src="//vk.com/js/api/openapi.js?146"></script>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand topnav" href="#">CarpFishing.Club</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Блог', blog_url %>
        </li>
        <li>
          <%= link_to 'Водоёмы', "https://iamfisher.ru/regions/", target: '_blank' %>
        </li>
        <li>
          <%= link_to "Магазин", 'https://carptimeshop.ru/', target: '_blank' %>
        </li>
        <li>
          <%= link_to 'Контакты', '#contact' %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<%= yield %>


<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <%= link_to 'Главная', root_url %>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <%= link_to 'Блог', blog_url %>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="http://www.iamfisher.ru/" target="_blank">Рыбалка в Пензенской области</a>
          </li>
        </ul>
        <p class="copyright text-muted small">Copyright &copy; CarpFishing.Club 2014 <% if  Time.now.year != 2014  %> - <%= Time.now.year %><% end %>. All Rights Reserved</p>
      </div>
    </div>
  </div>
</footer>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter25016279 = new Ya.Metrika({id:25016279,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/25016279" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'diarytrip'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>



<!-- VK Widget -->
<div id="vk_community_messages"></div>
<script type="text/javascript">
    VK.Widgets.CommunityMessages("vk_community_messages", 99626502, {expanded: "1",tooltipButtonText: "Есть вопрос?"});
</script>
</body>

</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<%= yield %>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>